Simple Language Parser
======================
Dave Roberts <dave.a.roberts@gmail.com>
:source-highlighter: pygments

Allow users to write a simple scripting to invoke your API.  Safer than `eval`.

Example Code
------------

See the `examples` directory for more

[source,lisp]
----
; Sample program that shows off syntax
set animals ( "lion" "tiger" "bear" "dog" "cat" )
push animals "monkey"
set family map ( "John" "Jacob" "Mary" "Maggie" ) name { obj { :firstname name } }
each family person {
  setprop person :lastname "Smith"
}
fun pet ( person animal ) {
  join ( getprop person :firstname " owns a " animal "!" )
}
pet first family first animals
set counter 0
loop {
  set counter + 1 counter
  getitem animals counter
  if ! = counter 1 { break } { }
}
json family
----

How to run
----------

You can use your own source files, or files from the `examples` directory

[source,console]
----
$ ./run examples/sample.lisp
$ ./run examples/fib.lisp
----

Background
----------
I studied computer science in college for six years.  I took a few courses in compilers and languages.  Despite having great professors, I didn't remember much about how to write a compiler.  This parser was created largely by trial and error.

I'm sure there are much better and more efficient ways to do this.

Lisp files
----------
The example files have a .lisp extension so that github and vim syntax highlight some keywords in the files.

Why‽
----
Let's say you have a platform that processes data from multiple other systems.  The data from every system is formatted in a different way.  Every time you want to accept a new type of document, the platform needs to be updated in order to understand the new format.  Another option is to accept both the document, and a script for how to process the document.
